name: flutter_app_upgrade
description: App 升级功能
version: 1.1.0
homepage: 'http://laomengit.com/plugin/upgrade.html'
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.flutter.flutter_app_upgrade
    pluginClass: FlutterAppUpgradePlugin
